app = "tv-review"
primary_region = "ams"

[build]

[env]
  NODE_ENV = "production"
  UPLOADS_DIR = "/data/uploads"

[deploy]
  release_command = "npx prisma migrate deploy"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1

[[mounts]]
  source = "uploads_data"
  destination = "/data/uploads"
