name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Stel secrets in
        run: |
          flyctl secrets set \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            NODE_ENV="production" \
            TRUSTED_SHOPS_LC_CLIENT_ID="${{ secrets.TRUSTED_SHOPS_LC_CLIENT_ID }}" \
            TRUSTED_SHOPS_LC_CLIENT_SECRET="${{ secrets.TRUSTED_SHOPS_LC_CLIENT_SECRET }}" \
            TRUSTED_SHOPS_LD_CLIENT_ID="${{ secrets.TRUSTED_SHOPS_LD_CLIENT_ID }}" \
            TRUSTED_SHOPS_LD_CLIENT_SECRET="${{ secrets.TRUSTED_SHOPS_LD_CLIENT_SECRET }}" \
            --app tv-review

      - name: Deploy
        run: flyctl deploy --remote-only
