name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Koppel database (eenmalig)
        run: flyctl postgres attach tv-review-db --app tv-review || true

      - name: Deploy
        run: flyctl deploy --remote-only
